[platformio]
default_envs = m5cardputer

[env:m5cardputer]
platform = espressif32 @ ^6.9.0
board = m5stack-stamps3
framework = arduino
monitor_speed = 115200
upload_speed = 1500000
board_upload.flash_size = 8MB
board_build.flash_size = 8MB
board_build.partitions = partitions.csv
board_build.arduino.memory_type = qio_opi
build_flags =
    -DBOARD_HAS_PSRAM
    -DARDUINO_USB_MODE=1
    -DARDUINO_USB_CDC_ON_BOOT=1
lib_deps =
    m5stack/M5Cardputer @ ^1.0.0
    bblanchon/ArduinoJson @ ^7.0.0

[env:native]
platform = native
lib_deps =
    bblanchon/ArduinoJson @ ^7.0.0
build_flags =
    -std=c++17
test_build_src = false
